services:
  - type: web
    name: route-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
  - type: pserv
    name: route-tracker-db
    databaseName: route_tracker
    databaseUser: route_tracker_user
    plan: free
